# How to author Executors: https://circleci.com/docs/2.0/reusing-config/#authoring-reusable-executors
description: >
  Just the bare minimum defualt for now
docker:
  - image: 'circleci/buildpack-deps@18.04-curl'
